[project]
dependencies = [
    "flet>=0.82.0",
    "flet-android-notifications==0.12.0",
]

[tool.flet.flutter.pubspec.dependency_overrides]
jni = "1.1.0"

[tool.flet.android.permission]
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.SCHEDULE_EXACT_ALARM" = true
"android.permission.RECEIVE_BOOT_COMPLETED" = true
