name: Build APK

on:
  push:
    branches: [main, nuevarama, versionparaapk]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev mesa-utils ninja-build libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev libgraphene-1.0-0

      - name: Install Flet
        run: pip install flet-cli

      - name: Build APK
        run: flet build apk --yes

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: build/apk/*.apk
